version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://blog-database:27017/blog
    ports:
      - '3000:3000'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://glorious-space-waddle-9grv5qvpvpv2xx4q-3000.app.github.dev/api/v1
    ports:
      - '3001:80'
    depends_on:
      - blog-backend
